React Capstone Project
silviatofana/react-capstone- pull request #1
Opened 2022-07-25 16:39 UTC by silviatofana

Chose an API, [Covid API](https://disease.sh/v3/covid-19/countries).
Built files structure for the App.
Made routes and navigation for the app.
Made sure that list of items were displayed and filtered with data from the API.
Create tests.
Style components.
Deploy project.
Record video for project.
Create a good REDME file

2022-07-25 20:07 UTC, prolajumokeoni requested changes
Hi @silviatofana, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used
✔️  Good design
✔️  Good PR title and Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-25 20:07 UTC, prolajumokeoni commented on github/workflows/linters.yml
> +        run: npx stylelint "**/*.{css,scss}"
- [ ] Kindly use the right [linters.yml](https://github.com/microverseinc/linters-config/blob/master/react-redux/.github/workflows/linters.yml) config file content  for react-redux from the microverse linters config repository

2022-07-25 20:07 UTC, prolajumokeoni commented on src/__tests__/App.test.js
> +});
- [ ] Kindly ensure tests are passing, currently, tests are failing 👍🏿  
![Screenshot_348](https://user-images.githubusercontent.com/69638013/180856604-525269a5-d885-4436-a298-c09110527cab.png)

2022-07-25 20:07 UTC, prolajumokeoni commented on src/pages/HomePage.js
> +const HomePage = () => {
- [ ] Good job filtering the incoming data, from api 👍🏿 Your home page should have a list of categories that could be filtered using given parameters, e.g. category name. Hint: Users should be able to filter by regions or you can create a search bar to filter countries alphabetically 😉

2022-07-25 20:07 UTC, prolajumokeoni commented on src/pages/HomePage.js
> +          <Link key={country.country} to={{ pathname: `/country/${country.country}` }}>
- [ ] In your project, it's not possible to navigate to the detail page by clicking the individual category item, in the home page, please fix this, see video below 👍🏿 

https://user-images.githubusercontent.com/69638013/180864367-9d73ef52-6198-41e4-bef3-cf1e48e0da59.mp4

2022-07-26 13:38 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @silviatofana        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-26 13:39 UTC, silviatofana commented
WOOOOWWWWWWW THANKSSSSSS

2022-07-26 13:39 UTC, merged